### ISSUE TITLE
[Task]: Dashboard Wireframes

### ISSUE THREAD

**Issue by yashsehgal** [yashsehgal/prepmeup#1]
## Dashboard Wireframes
- [x] Create a list of features to be added
- [x] Create a rough design of how the UI will look like and audit the design with shadcn components.

**Comment by shristigupta12** [comment]
We can take reference from this wireframe to the build the dashboard interface. :smile_cat: 
Let's look for similar [shadcn](https://ui.shadcn.com/ ) components. :two_women_holding_hands: 

![image](https://github.com/yashsehgal/prepmeup/assets/91966319/456fa4ee-e457-48a5-a716-feced66197eb)

**Comment by yashsehgal** [comment]
Great 🍕 We can start adding utility components according to this wireframe. Progress for the same will be tracked here

- #4
